<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Browse\Enums;

use SapientPro\EbayTraditionalSDK\Browse\Enums\ItemGroupTypeEnum;
use PHPUnit\Framework\TestCase;

class ItemGroupTypeEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Browse\Enums\ItemGroupTypeEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new ItemGroupTypeEnum();
    }
}
