<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\PostOrder\Types;

use SapientPro\EbayTraditionalSDK\PostOrder\Types\GetInquiryRestResponse;
use PHPUnit\Framework\TestCase;

class GetInquiryRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\PostOrder\Types\GetInquiryRestResponse', $this->obj);
    }

    public function testExtendsInquiryDetailsResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\PostOrder\Types\InquiryDetailsResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetInquiryRestResponse();
    }
}
