<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\PostOrder\Types;

use SapientPro\EbayTraditionalSDK\PostOrder\Types\IssueCaseRefundRestRequest;
use PHPUnit\Framework\TestCase;

class IssueCaseRefundRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\PostOrder\Types\IssueCaseRefundRestRequest', $this->obj);
    }

    public function testExtendsCaseVoluntaryRefundRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\PostOrder\Types\CaseVoluntaryRefundRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new IssueCaseRefundRestRequest();
    }
}
