<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Types;

use SapientPro\EbayTraditionalSDK\Account\Types\CreateAReturnPolicyRestRequest;
use PHPUnit\Framework\TestCase;

class CreateAReturnPolicyRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\CreateAReturnPolicyRestRequest', $this->obj);
    }

    public function testExtendsReturnPolicyRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\ReturnPolicyRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateAReturnPolicyRestRequest();
    }
}
