<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Types;

use SapientPro\EbayTraditionalSDK\Account\Types\CreateAPaymentPolicyRestResponse;
use PHPUnit\Framework\TestCase;

class CreateAPaymentPolicyRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\CreateAPaymentPolicyRestResponse', $this->obj);
    }

    public function testExtendsSetPaymentPolicyResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\SetPaymentPolicyResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateAPaymentPolicyRestResponse();
    }
}
