<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Types;

use SapientPro\EbayTraditionalSDK\Account\Types\CreateAFulfillmentPolicyRestRequest;
use PHPUnit\Framework\TestCase;

class CreateAFulfillmentPolicyRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\CreateAFulfillmentPolicyRestRequest', $this->obj);
    }

    public function testExtendsFulfillmentPolicyRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\FulfillmentPolicyRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateAFulfillmentPolicyRestRequest();
    }
}
