<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Types;

use SapientPro\EbayTraditionalSDK\Account\Types\GetAReturnPolicyByNameRestResponse;
use PHPUnit\Framework\TestCase;

class GetAReturnPolicyByNameRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\GetAReturnPolicyByNameRestResponse', $this->obj);
    }

    public function testExtendsReturnPolicy()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\ReturnPolicy', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetAReturnPolicyByNameRestResponse();
    }
}
