<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Types;

use SapientPro\EbayTraditionalSDK\Account\Types\GetAllSalesTaxTablesRestResponse;
use PHPUnit\Framework\TestCase;

class GetAllSalesTaxTablesRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\GetAllSalesTaxTablesRestResponse', $this->obj);
    }

    public function testExtendsSalesTaxes()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\SalesTaxes', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetAllSalesTaxTablesRestResponse();
    }
}
