<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Types;

use SapientPro\EbayTraditionalSDK\Account\Types\GetOptedInProgramsRestResponse;
use PHPUnit\Framework\TestCase;

class GetOptedInProgramsRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\GetOptedInProgramsRestResponse', $this->obj);
    }

    public function testExtendsPrograms()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Types\Programs', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetOptedInProgramsRestResponse();
    }
}
