<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Taxonomy\Types;

use SapientPro\EbayTraditionalSDK\Taxonomy\Types\GetACategorySubtreeRestResponse;
use PHPUnit\Framework\TestCase;

class GetACategorySubtreeRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Taxonomy\Types\GetACategorySubtreeRestResponse', $this->obj);
    }

    public function testExtendsCategorySubtree()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Taxonomy\Types\CategorySubtree', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetACategorySubtreeRestResponse();
    }
}
