<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Taxonomy\Types;

use SapientPro\EbayTraditionalSDK\Taxonomy\Types\GetItemAspectsForCategoryRestResponse;
use PHPUnit\Framework\TestCase;

class GetItemAspectsForCategoryRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Taxonomy\Types\GetItemAspectsForCategoryRestResponse', $this->obj);
    }

    public function testExtendsAspectMetadata()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Taxonomy\Types\AspectMetadata', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetItemAspectsForCategoryRestResponse();
    }
}
