<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Fulfillment\Enums;

use SapientPro\EbayTraditionalSDK\Fulfillment\Enums\PaymentStatusEnum;
use PHPUnit\Framework\TestCase;

class PaymentStatusEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Fulfillment\Enums\PaymentStatusEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new PaymentStatusEnum();
    }
}
