<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Browse\Types;

use SapientPro\EbayTraditionalSDK\Browse\Types\GetItemsByItemGroupRestResponse;
use PHPUnit\Framework\TestCase;

class GetItemsByItemGroupRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Browse\Types\GetItemsByItemGroupRestResponse', $this->obj);
    }

    public function testExtendsItems()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Browse\Types\Items', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetItemsByItemGroupRestResponse();
    }
}
