<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Browse\Types;

use SapientPro\EbayTraditionalSDK\Browse\Types\SearchForItemsRestResponse;
use PHPUnit\Framework\TestCase;

class SearchForItemsRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Browse\Types\SearchForItemsRestResponse', $this->obj);
    }

    public function testExtendsSearchPagedCollection()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Browse\Types\SearchPagedCollection', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new SearchForItemsRestResponse();
    }
}
