<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\ProductMetadata\Enums;

use SapientPro\EbayTraditionalSDK\ProductMetadata\Enums\DatasetValue;
use PHPUnit\Framework\TestCase;

class DatasetValueTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\ProductMetadata\Enums\DatasetValue', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new DatasetValue();
    }
}
