<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Account\Enums;

use SapientPro\EbayTraditionalSDK\Account\Enums\PaymentInstrumentBrandEnum;
use PHPUnit\Framework\TestCase;

class PaymentInstrumentBrandEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Account\Enums\PaymentInstrumentBrandEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new PaymentInstrumentBrandEnum();
    }
}
