<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Catalog\Enums;

use SapientPro\EbayTraditionalSDK\Catalog\Enums\AspectModeEnum;
use PHPUnit\Framework\TestCase;

class AspectModeEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Catalog\Enums\AspectModeEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new AspectModeEnum();
    }
}
