<?php

declare(strict_types=1);

namespace SapientPro\EbayTraditionalSDK\Marketing\Enums;

class ReportTypeEnum
{
    public const C_ACCOUNT_PERFORMANCE_REPORT = 'ACCOUNT_PERFORMANCE_REPORT';
    public const C_CAMPAIGN_PERFORMANCE_REPORT = 'CAMPAIGN_PERFORMANCE_REPORT';
    public const C_CAMPAIGN_PERFORMANCE_SUMMARY_REPORT = 'CAMPAIGN_PERFORMANCE_SUMMARY_REPORT';
    public const C_INVENTORY_PERFORMANCE_REPORT = 'INVENTORY_PERFORMANCE_REPORT';
    public const C_LISTING_PERFORMANCE_REPORT = 'LISTING_PERFORMANCE_REPORT';
}
