<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Finding\Enums;

use SapientPro\EbayTraditionalSDK\Finding\Enums\ItemFilterType;
use PHPUnit\Framework\TestCase;

class ItemFilterTypeTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Finding\Enums\ItemFilterType', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new ItemFilterType();
    }
}
