<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Metadata\Types;

use SapientPro\EbayTraditionalSDK\Metadata\Types\GetPoliciesForAutoPartsCompatibilityRestResponse;
use PHPUnit\Framework\TestCase;

class GetPoliciesForAutoPartsCompatibilityRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\GetPoliciesForAutoPartsCompatibilityRestResponse', $this->obj);
    }

    public function testExtendsAutomotivePartsCompatibilityPolicyResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\AutomotivePartsCompatibilityPolicyResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetPoliciesForAutoPartsCompatibilityRestResponse();
    }
}
