<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Metadata\Types;

use SapientPro\EbayTraditionalSDK\Metadata\Types\GetPoliciesForListingStructuresRestResponse;
use PHPUnit\Framework\TestCase;

class GetPoliciesForListingStructuresRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\GetPoliciesForListingStructuresRestResponse', $this->obj);
    }

    public function testExtendsListingStructurePolicyResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\ListingStructurePolicyResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetPoliciesForListingStructuresRestResponse();
    }
}
