<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Metadata\Types;

use SapientPro\EbayTraditionalSDK\Metadata\Types\GetPoliciesForNegotiatedPriceRestResponse;
use PHPUnit\Framework\TestCase;

class GetPoliciesForNegotiatedPriceRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\GetPoliciesForNegotiatedPriceRestResponse', $this->obj);
    }

    public function testExtendsNegotiatedPricePolicyResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\NegotiatedPricePolicyResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetPoliciesForNegotiatedPriceRestResponse();
    }
}
