<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Metadata\Types;

use SapientPro\EbayTraditionalSDK\Metadata\Types\GetSalesTaxJurisdictionsRestResponse;
use PHPUnit\Framework\TestCase;

class GetSalesTaxJurisdictionsRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\GetSalesTaxJurisdictionsRestResponse', $this->obj);
    }

    public function testExtendsSalesTaxJurisdictions()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Metadata\Types\SalesTaxJurisdictions', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetSalesTaxJurisdictionsRestResponse();
    }
}
