<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\RelatedItemsManagement\Enums;

use SapientPro\EbayTraditionalSDK\RelatedItemsManagement\Enums\DiscountTypeEnum;
use PHPUnit\Framework\TestCase;

class DiscountTypeEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\RelatedItemsManagement\Enums\DiscountTypeEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new DiscountTypeEnum();
    }
}
