<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Order\Types;

use SapientPro\EbayTraditionalSDK\Order\Types\InitiateCheckoutSessionRestRequest;
use PHPUnit\Framework\TestCase;

class InitiateCheckoutSessionRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Order\Types\InitiateCheckoutSessionRestRequest', $this->obj);
    }

    public function testExtendsCreateSignInCheckoutSessionRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Order\Types\CreateSignInCheckoutSessionRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new InitiateCheckoutSessionRestRequest();
    }
}
