<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Order\Types;

use SapientPro\EbayTraditionalSDK\Order\Types\UpdateQuantityForLineItemRestRequest;
use PHPUnit\Framework\TestCase;

class UpdateQuantityForLineItemRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Order\Types\UpdateQuantityForLineItemRestRequest', $this->obj);
    }

    public function testExtendsUpdateQuantity()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Order\Types\UpdateQuantity', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new UpdateQuantityForLineItemRestRequest();
    }
}
