<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Catalog\Types;

use SapientPro\EbayTraditionalSDK\Catalog\Types\CreateChangeRequestRestRequest;
use PHPUnit\Framework\TestCase;

class CreateChangeRequestRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Catalog\Types\CreateChangeRequestRestRequest', $this->obj);
    }

    public function testExtendsCreateChangeRequestPayload()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Catalog\Types\CreateChangeRequestPayload', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateChangeRequestRestRequest();
    }
}
