<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Catalog\Types;

use SapientPro\EbayTraditionalSDK\Catalog\Types\GetProductMetadataRestResponse;
use PHPUnit\Framework\TestCase;

class GetProductMetadataRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Catalog\Types\GetProductMetadataRestResponse', $this->obj);
    }

    public function testExtendsProductMetadata()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Catalog\Types\ProductMetadata', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetProductMetadataRestResponse();
    }
}
