<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Analytics\Types;

use SapientPro\EbayTraditionalSDK\Analytics\Types\GetASpecificSellerProfileRestResponse;
use PHPUnit\Framework\TestCase;

class GetASpecificSellerProfileRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Analytics\Types\GetASpecificSellerProfileRestResponse', $this->obj);
    }

    public function testExtendsStandardsProfile()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Analytics\Types\StandardsProfile', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetASpecificSellerProfileRestResponse();
    }
}
