<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Analytics\Types;

use SapientPro\EbayTraditionalSDK\Analytics\Types\GetAllSellerProfilesRestResponse;
use PHPUnit\Framework\TestCase;

class GetAllSellerProfilesRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Analytics\Types\GetAllSellerProfilesRestResponse', $this->obj);
    }

    public function testExtendsFindSellerStandardsProfilesResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Analytics\Types\FindSellerStandardsProfilesResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetAllSellerProfilesRestResponse();
    }
}
