<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Feed\Enums;

use SapientPro\EbayTraditionalSDK\Feed\Enums\CurrencyCodeEnum;
use PHPUnit\Framework\TestCase;

class CurrencyCodeEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Feed\Enums\CurrencyCodeEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CurrencyCodeEnum();
    }
}
