<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Marketing\Types;

use SapientPro\EbayTraditionalSDK\Marketing\Types\BulkCreateAdsByInventoryReferenceRestResponse;
use PHPUnit\Framework\TestCase;

class BulkCreateAdsByInventoryReferenceRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\BulkCreateAdsByInventoryReferenceRestResponse', $this->obj);
    }

    public function testExtendsBulkCreateAdsByInventoryReferenceResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\BulkCreateAdsByInventoryReferenceResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new BulkCreateAdsByInventoryReferenceRestResponse();
    }
}
