<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Marketing\Types;

use SapientPro\EbayTraditionalSDK\Marketing\Types\BulkDeleteAdsByListingIDRestRequest;
use PHPUnit\Framework\TestCase;

class BulkDeleteAdsByListingIDRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\BulkDeleteAdsByListingIDRestRequest', $this->obj);
    }

    public function testExtendsBulkDeleteAdRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\BulkDeleteAdRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new BulkDeleteAdsByListingIDRestRequest();
    }
}
