<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Marketing\Types;

use SapientPro\EbayTraditionalSDK\Marketing\Types\BulkDeleteAdsByInventoryReferenceRestResponse;
use PHPUnit\Framework\TestCase;

class BulkDeleteAdsByInventoryReferenceRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\BulkDeleteAdsByInventoryReferenceRestResponse', $this->obj);
    }

    public function testExtendsBulkDeleteAdsByInventoryReferenceResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\BulkDeleteAdsByInventoryReferenceResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new BulkDeleteAdsByInventoryReferenceRestResponse();
    }
}
