<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Marketing\Types;

use SapientPro\EbayTraditionalSDK\Marketing\Types\CreateAdsByInventoryReferenceRestRequest;
use PHPUnit\Framework\TestCase;

class CreateAdsByInventoryReferenceRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\CreateAdsByInventoryReferenceRestRequest', $this->obj);
    }

    public function testExtendsCreateAdsByInventoryReferenceRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\CreateAdsByInventoryReferenceRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateAdsByInventoryReferenceRestRequest();
    }
}
