<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Marketing\Types;

use SapientPro\EbayTraditionalSDK\Marketing\Types\CreateCampaignRestRequest;
use PHPUnit\Framework\TestCase;

class CreateCampaignRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\CreateCampaignRestRequest', $this->obj);
    }

    public function testExtendsCreateCampaignRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\CreateCampaignRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateCampaignRestRequest();
    }
}
