<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Marketing\Types;

use SapientPro\EbayTraditionalSDK\Marketing\Types\UpdateBidRestRequest;
use PHPUnit\Framework\TestCase;

class UpdateBidRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\UpdateBidRestRequest', $this->obj);
    }

    public function testExtendsUpdateBidPercentageRequest()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Marketing\Types\UpdateBidPercentageRequest', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new UpdateBidRestRequest();
    }
}
