<?php

declare(strict_types=1);

namespace SapientPro\EbayTraditionalSDK\PostOrder\Enums;

class CancelCloseReasonEnum
{
    public const C_BUYER_CONFIRM_NOT_PAID = 'BUYER_CONFIRM_NOT_PAID';
    public const C_BUYER_CONFIRM_REFUND = 'BUYER_CONFIRM_REFUND';
    public const C_BUYER_CONFIRM_TIMEOUT_NON_PAYPAL_PAID = 'BUYER_CONFIRM_TIMEOUT_NON_PAYPAL_PAID';
    public const C_BUYER_CONFIRM_TIMEOUT_PAYPAL_PAID = 'BUYER_CONFIRM_TIMEOUT_PAYPAL_PAID';
    public const C_FULL_REFUNDED = 'FULL_REFUNDED';
    public const C_INELIGIBLE_FOR_CANCEL = 'INELIGIBLE_FOR_CANCEL';
    public const C_REFUND_FAILED = 'REFUND_FAILED';
    public const C_SELLER_APPROVE_TIMEOUT_PAID = 'SELLER_APPROVE_TIMEOUT_PAID';
    public const C_SELLER_APPROVE_TIMEOUT_UNPAID = 'SELLER_APPROVE_TIMEOUT_UNPAID';
    public const C_SELLER_APPROVE_UNPAID = 'SELLER_APPROVE_UNPAID';
    public const C_SELLER_DECLINE = 'SELLER_DECLINE';
    public const C_SYSTEM_NOTIFY_SHIPPING_STATUS = 'SYSTEM_NOTIFY_SHIPPING_STATUS';
    public const C_UNKNOWN = 'UNKNOWN';
}
