<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Compliance\Enums;

use SapientPro\EbayTraditionalSDK\Compliance\Enums\ComplianceTypeEnum;
use PHPUnit\Framework\TestCase;

class ComplianceTypeEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Compliance\Enums\ComplianceTypeEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new ComplianceTypeEnum();
    }
}
