<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\MerchantData\Types;

use SapientPro\EbayTraditionalSDK\MerchantData\Types\ReviseItemRequestType;
use PHPUnit\Framework\TestCase;

class ReviseItemRequestTypeTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\MerchantData\Types\ReviseItemRequestType', $this->obj);
    }

    public function testExtendsAbstractRequestType()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\MerchantData\Types\AbstractRequestType', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new ReviseItemRequestType();
    }
}
