<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Inventory\Types;

use SapientPro\EbayTraditionalSDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestResponse;
use PHPUnit\Framework\TestCase;

class CreateOrReplaceInventoryItemGroupRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Inventory\Types\CreateOrReplaceInventoryItemGroupRestResponse', $this->obj);
    }

    public function testExtendsBaseResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Inventory\Types\BaseResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateOrReplaceInventoryItemGroupRestResponse();
    }
}
