<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Inventory\Types;

use SapientPro\EbayTraditionalSDK\Inventory\Types\GetInventoryLocationsRestResponse;
use PHPUnit\Framework\TestCase;

class GetInventoryLocationsRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Inventory\Types\GetInventoryLocationsRestResponse', $this->obj);
    }

    public function testExtendsLocationResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Inventory\Types\LocationResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetInventoryLocationsRestResponse();
    }
}
