<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Feed\Types;

use SapientPro\EbayTraditionalSDK\Feed\Types\GetItemFeedRestResponse;
use PHPUnit\Framework\TestCase;

class GetItemFeedRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Feed\Types\GetItemFeedRestResponse', $this->obj);
    }

    public function testExtendsItemFeedResponse()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Feed\Types\ItemFeedResponse', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetItemFeedRestResponse();
    }
}
