<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Finding\Types;

use SapientPro\EbayTraditionalSDK\Finding\Types\CategoryHistogram;
use PHPUnit\Framework\TestCase;

class CategoryHistogramTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Finding\Types\CategoryHistogram', $this->obj);
    }

    public function testExtendsCategory()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Finding\Types\Category', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CategoryHistogram();
    }
}
