<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Compliance\Types;

use SapientPro\EbayTraditionalSDK\Compliance\Types\GetListingViolationsRestResponse;
use PHPUnit\Framework\TestCase;

class GetListingViolationsRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Compliance\Types\GetListingViolationsRestResponse', $this->obj);
    }

    public function testExtendsPagedComplianceViolationCollection()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Compliance\Types\PagedComplianceViolationCollection', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetListingViolationsRestResponse();
    }
}
