<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Compliance\Types;

use SapientPro\EbayTraditionalSDK\Compliance\Types\GetListingViolationsSummaryRestResponse;
use PHPUnit\Framework\TestCase;

class GetListingViolationsSummaryRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Compliance\Types\GetListingViolationsSummaryRestResponse', $this->obj);
    }

    public function testExtendsComplianceSummary()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Compliance\Types\ComplianceSummary', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetListingViolationsSummaryRestResponse();
    }
}
