<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Order\Enums;

use SapientPro\EbayTraditionalSDK\Order\Enums\PurchaseOrderStatusEnum;
use PHPUnit\Framework\TestCase;

class PurchaseOrderStatusEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Order\Enums\PurchaseOrderStatusEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new PurchaseOrderStatusEnum();
    }
}
