<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Analytics\Enums;

use SapientPro\EbayTraditionalSDK\Analytics\Enums\DataTypeEnum;
use PHPUnit\Framework\TestCase;

class DataTypeEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Analytics\Enums\DataTypeEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new DataTypeEnum();
    }
}
