<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Fulfillment\Types;

use SapientPro\EbayTraditionalSDK\Fulfillment\Types\CreateAShippingFulfillmentRestRequest;
use PHPUnit\Framework\TestCase;

class CreateAShippingFulfillmentRestRequestTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Fulfillment\Types\CreateAShippingFulfillmentRestRequest', $this->obj);
    }

    public function testExtendsShippingFulfillmentDetails()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Fulfillment\Types\ShippingFulfillmentDetails', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new CreateAShippingFulfillmentRestRequest();
    }
}
