<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Fulfillment\Types;

use SapientPro\EbayTraditionalSDK\Fulfillment\Types\GetAShippingFulfillmentRestResponse;
use PHPUnit\Framework\TestCase;

class GetAShippingFulfillmentRestResponseTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Fulfillment\Types\GetAShippingFulfillmentRestResponse', $this->obj);
    }

    public function testExtendsShippingFulfillment()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Fulfillment\Types\ShippingFulfillment', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new GetAShippingFulfillmentRestResponse();
    }
}
