<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Inventory\Enums;

use SapientPro\EbayTraditionalSDK\Inventory\Enums\LengthUnitOfMeasureEnum;
use PHPUnit\Framework\TestCase;

class LengthUnitOfMeasureEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Inventory\Enums\LengthUnitOfMeasureEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new LengthUnitOfMeasureEnum();
    }
}
