<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SapientPro\EbayTraditionalSDK\Tests\Inventory\Enums;

use SapientPro\EbayTraditionalSDK\Inventory\Enums\TimeDurationUnitEnum;
use PHPUnit\Framework\TestCase;

class TimeDurationUnitEnumTest extends TestCase
{
    private $obj;

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\SapientPro\EbayTraditionalSDK\Inventory\Enums\TimeDurationUnitEnum', $this->obj);
    }

    protected function setUp(): void
    {
        $this->obj = new TimeDurationUnitEnum();
    }
}
